import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          <Link href={"/ssr-demo"}>
            <a>SSR Demo</a>
          </Link>
        </p>

        <p>
          <Link href={"/ssg-demo"}>
            <a>SSG Demo</a>
          </Link>
        </p>

        <p>
          <Link href={"/isr-demo"}>
            <a>ISR Demo</a>
          </Link>
        </p>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        ></a>
      </footer>
    </div>
  );
};

export default Home;
