import Head from "next/head";
import { GetStaticProps } from "next";
import Link from "next/link";

type Props = { nowDate: string; pageTitle: string };

export default function ISRDemo(props: Props) {
  return (
    <div>
      <Head>
        <title>{props.pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>{props.pageTitle}</h2>
        <p>What time is it now?</p>
        <p>It&apos;s {props.nowDate}.</p>
        <p>
          <Link href={"/"}>
            <a>Go back</a>
          </Link>
        </p>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps<Props> = async (ctx) => {
  return {
    props: {
      nowDate: new Date().toLocaleString(),
      pageTitle: "ISR Demo",
    },
    revalidate: 5, // ISR settings
  };
};
